name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2.3.0
        with:
          ref: ${{ github.ref }}

      - name: Install packages
        run: yarn

      - name: Build application
        run: yarn build
